GTCEuStartupEvents.registry('gtceu:material', e => {
//ores
    e.create('bismuthinite')
        .dust().ore()
        .components('2x bismuth', '3x sulfur')
        .color(0x6e9798).secondaryColor(0x667f80).iconSet('shiny')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    e.create('calaverite')
        .dust().ore()
        .components('1x gold', '2x tellurium')
        .color(0x4f4c3a).secondaryColor(0x61604d).iconSet('shiny')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    e.create('carnotite')
        .dust().ore()
        .components('2x potassium', '2x uranium', '12x oxygen', '2x vanadium', '3x hydrogen')
        .color(0xd2a84c).secondaryColor(0x805911).iconSet('dull')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    e.create('ferberite')
        .dust().ore()
        .components('1x iron', '1x tungsten', '4x oxygen')
        .color(0x99a29d).secondaryColor(0x020706).iconSet('metallic')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    e.create('fluorite')
        .dust().ore()
        .components('1x calcium', '2x fluorine')
        .color(0x2b6448).secondaryColor(0x264031).iconSet('diamond')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    e.create('keamanite')
        .dust().ore()
        .components('1x trinium', '1x tungsten', '2x sulfur')
        .color(0x5f56c42).secondaryColor(0xfa2714).iconSet('fine')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    e.create('rammelsbergite')
        .dust().ore()
        .components('1x nickel', '2x arsenic')
        .color(0x60645e).secondaryColor(0x494f40).iconSet('fine')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    e.create('raw_electrum')
        .dust().ore()
        .components('1x gold', '1x silver')
        .color(0xcccc72).secondaryColor(0xb3642e).iconSet('metallic')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    e.create('skutterudite')
        .dust().ore()
        .components('1x cobalt', '3x arsenic')
        .color(0x817e82).secondaryColor(0x3b3431).iconSet('shiny')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    e.create('stannite')
        .dust().ore()
        .components('2x copper', '1x iron', '1x tin', '4x sulfur')
        .color(0x3C392e).secondaryColor(0x17130e).iconSet('dull')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    e.create('smithsonite')
        .dust().ore()
        .components('1x zinc', '1x carbon', '3x oxygen')
        .color(0x229594).secondaryColor(0x475d5d).iconSet('rough')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    e.create('sylvanite')
        .dust().ore()
        .components('1x silver', '1x gold', '2x tellurium')
        .color(0x5c5048).secondaryColor(0x575655).iconSet('metallic')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    e.create('vanadinite')
        .dust().ore()
        .components('5x lead', '3x vanadium', '12x oxygen', '1x chlorine')
        .color(0xa7311e).secondaryColor(0x9a1A05).iconSet('diamond')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    e.create('wolframite')
        .dust().ore()
        .components('1x iron', '1x manganese', '1x tungsten', '4x oxygen')
        .color(0x584f52).secondaryColor(0x565050).iconSet('dull')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    e.create('xenotime')
        .dust().ore()
        .components('1x yttrium', '1x phosphorus', '4x oxygen')
        .color(0x623f32).secondaryColor(0x4a4339).iconSet('diamond')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    e.create('zircon')
        .dust().ore()
        .components('1x zirconium', '1x silicon', '4x oxygen')
        .color(0xae260c).secondaryColor(0x710b00).iconSet('diamond')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
})
GTCEuStartupEvents.materialModification(e => {
	GTMaterials.get('carnotite').setFormula('K2(UO2)2(VO4)2(H2O)3')
    GTMaterials.get('vanadinite').setFormula('Pb5(VO4)3Cl')
	GTMaterials.get('wolframite').setFormula('(Fe,Mn)WO4')
})