GTCEuServerEvents.oreVeins(e => {
    e.remove('gtceu:redstone_vein')
    e.remove('gtceu:naquadah_vein')
    e.remove('gtceu:magnetite_vein_end')
    e.remove('gtceu:beryllium_vein')
    e.remove('gtceu:copper_vein')
    e.remove('gtceu:scheelite_vein')

    e.modify('gtceu:tetrahedrite_vein', vein => {vein.dimensions('minecraft:overworld')
        vein.biomes('#minecraft:is_overworld')})

    e.modify('gtceu:monazite_vein', vein => { vein.dimensions('minecraft:overworld')
        vein.biomes('#minecraft:is_overworld')})

    e.modify('gtceu:saltpeter_vein', vein => {vein.dimensions('minecraft:overworld')
        vein.biomes('#minecraft:is_overworld')})

    e.add('kubejs:copper_iron_vein', vein => {
        vein.weight(80)
        vein.clusterSize(40)
        vein.density(0.25)
        vein.discardChanceOnAirExposure(0)
        vein.layer('deepslate')
        vein.dimensions('minecraft:overworld')
        vein.biomes('#minecraft:is_overworld')
        vein.heightRangeUniform(-40, 10)
        vein.veinedVeinGenerator(generator => generator
            .oreBlock(GTMaterials.Chalcopyrite, 4)
            .oreBlock(GTMaterials.Pyrite, 4)
            .oreBlock(GTMaterials.Copper, 4)
            .rareBlock(GTMaterials.Hematite, 1)
            .rareBlockChance(0.25)
            .veininessThreshold(0.1)
            .maxRichnessThreshold(0.3)
            .minRichness(0.3)
            .maxRichness(0.5)
            .edgeRoundoffBegin(10)
            .maxEdgeRoundoff(0.2))
        vein.surfaceIndicatorGenerator(indicator => indicator
            .surfaceRock(GTMaterials.Chalcopyrite)
            .placement('above')
            .density(0.4)
            .radius(5))
    })

    e.add('kubejs:tunstate_vein', vein => {
        vein.weight(20)
        vein.clusterSize(40)
        vein.density(0.25)
        vein.discardChanceOnAirExposure(0)
        vein.layer('deepslate')
        vein.dimensions('minecraft:overworld')
        vein.biomes('#minecraft:is_overworld')
        vein.heightRangeUniform(20, 60)
        vein.veinedVeinGenerator(generator => generator
            .oreBlock(GTMaterials.Tungstate, 4)
            .oreBlock(GTMaterials.Scheelite, 4)
            .oreBlock(GTMaterials.get('wolframite'), 4)
            .rareBlock(GTMaterials.Powellite, 1)
            .rareBlockChance(0.25)
            .veininessThreshold(0.1)
            .maxRichnessThreshold(0.3)
            .minRichness(0.3)
            .maxRichness(0.5)
            .edgeRoundoffBegin(10)
            .maxEdgeRoundoff(0.2))
        vein.surfaceIndicatorGenerator(indicator => indicator
            .surfaceRock(GTMaterials.Tungstate)
            .placement('above')
            .density(0.4)
            .radius(5))
    })

})